# Generated by Django 4.2.2 on 2023-06-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_login_history_users_registered_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login_history',
            name='Email',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_login_history',
            name='Time',
            field=models.CharField(default='09:01:42', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='Address_1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='Address_2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='Address_3',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='City',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='Contact_Number',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='Country',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='First_Name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='Last_Name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='Recovery_Email',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='Street',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
