# Generated by Django 4.2.2 on 2023-06-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_login_history_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Address_1',
            new_name='Address1',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Address_2',
            new_name='Address2',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Address_3',
            new_name='Address3',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Contact_Number',
            new_name='ContactNumber',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='First_Name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Last_Name',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Recovery_Email',
            new_name='RecoveryEmail',
        ),
        migrations.AlterField(
            model_name='user_login_history',
            name='Time',
            field=models.CharField(default='09:45:49', max_length=50),
        ),
    ]
