# Generated by Django 4.2.2 on 2023-06-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_rename_address_1_users_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login_history',
            name='Time',
            field=models.CharField(default='09:47:12', max_length=50),
        ),
    ]
