# Generated by Django 4.2.2 on 2023-07-24 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_user_login_history_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='CountryCode',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_login_history',
            name='Date',
            field=models.CharField(default=datetime.date(2023, 7, 24), max_length=50),
        ),
        migrations.AlterField(
            model_name='user_login_history',
            name='Time',
            field=models.CharField(default='17:41:53', max_length=50),
        ),
    ]
