# Generated by Django 4.2.2 on 2023-07-26 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_users_countrycode_alter_user_login_history_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login_history',
            name='Date',
            field=models.CharField(default=datetime.date(2023, 7, 26), max_length=50),
        ),
        migrations.AlterField(
            model_name='user_login_history',
            name='Time',
            field=models.CharField(default='09:17:52', max_length=50),
        ),
    ]
