# Generated by Django 4.2.2 on 2023-07-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_user_login_history_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login_history',
            name='Time',
            field=models.CharField(default='09:50:09', max_length=50),
        ),
    ]
