# Generated by Django 4.2.2 on 2023-07-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_user_login_history_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login_history',
            name='Time',
            field=models.CharField(default='10:48:53', max_length=50),
        ),
    ]
