# Generated by Django 4.2.2 on 2023-06-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='None', max_length=50)),
                ('Icon', models.ImageField(upload_to='Product_Icons')),
                ('ImageA', models.ImageField(upload_to='Product_Images_A')),
                ('ImageB', models.ImageField(upload_to='Product_Images_A')),
                ('ImageC', models.ImageField(upload_to='Product_Images_A')),
                ('ImageD', models.ImageField(upload_to='Product_Images_D')),
                ('Description', models.CharField(default='None', max_length=200)),
                ('DownloadLink', models.CharField(default='None', max_length=200)),
                ('Installs', models.CharField(default='None', max_length=50)),
            ],
        ),
    ]
