# Generated by Django 4.2.2 on 2023-07-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserEmail', models.CharField(max_length=50)),
                ('Product', models.CharField(max_length=50)),
            ],
        ),
    ]
