# Generated by Django 4.2.2 on 2023-07-26 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_userproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproducts',
            old_name='Product',
            new_name='ProductName',
        ),
    ]
