# Generated by Django 4.2.2 on 2023-07-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_rename_product_userproducts_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproducts',
            name='DueDate',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
